# Generated by Django 4.2 on 2023-04-14 15:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MusteriModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi', models.CharField(max_length=50)),
                ('soyadi', models.CharField(max_length=50)),
                ('eposta', models.EmailField(max_length=254)),
                ('adres', models.TextField()),
                ('kayit_zaman', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
